def murder():
    print('\tRota do Jack:Em um bairro de Londres, sons abafados ecoam de uma rua consumida por nada além das sombras e\ndos ratos que por ali passam, os sons das gotas da chuva parecem estridentes se comparados ao total silêncio do beco escuro,\nos sons abafados cessam, a vítima se debate em uma fútil tentativa de resistência, a última fagulha de esperança se\nesvai de seus olhos, suas pupilas se dilatam e finalmente, seu corpo desmorona contra o chão, a garota não voltaria para\nseus filhos naquela noite, e em nenhuma das subsequentes.O misterioso homem contempla sua obra, sua consciência funciona por\nbreves períodos, o mesmo sabe que cometeu uma atrocidade, entretanto, sua mente diluída com traumas e angústias altera\nsua concepção da realidade, ele acredita ter realizado algo bom para o mundo.')
    jack_choices1 = input('\tA figura sombria escuta um som estrondoso na boca do beco, ao analisar o local, o mesmo presencia uma garota de\ncabelos negros, ele não poderia deixar que a testemunha visse seu trabalho antes da polícia, ele se ergue com velocidade:\nFugir(Digite "f")/Perseguir(Digite "p")/')
    if (jack_choices1=='f'):
        print('\tO misterioso homem opta por não atacar a testemunha e começa a correr contra às sombras, a\ngarota grita em desespero e policiais se aproximam rapidamente do local, o esguio\nculpado corre o risco de brevemente ser apanhado.')
        jack_sub_choices_escape=input('\tEle corre e chega em um canto sem saída que localiza-se ao lado de um\naçougue, duas opções transcorrem pelos seus olhos:\nPular contra a janela do açougue(Digite "j")/Lutar contra os policiais(Digite "l")')
        if (jack_sub_choices_escape=='j'):
            print('\tEle se joga contra a janela e o vidro se estraçalha, o funcionário do local olha espantado para a figura\nque utiliza uma máscara de pano ensanguentada, os policiais se aproximam do local com lentidão,\no garoto abre a boca e prepara-se para gritar.')
            jack_jump_window=input('Pegar a faca cravada em um pedaço de carne no balcão e atacar o garoto.(Digite "p")/Dar um soco no garoto.(Digite "d").')
            if (jack_jump_window=='p'):
                print('\tO encapuzado pega a faca com agilidade, ele estava familiarizado a controlar uma lâmina, ele enfia a faca\nna mão do garoto, logo após isso, rapidamente coloca seus dedos sobre a boca do mesmo, os gritos\nse tornam meros suspiros desesperados, o assassino então puxa o garoto para trás do balcão e começa a enforca-lo\naté que o brilho de seus olhos desapareça, a polícia não ouviu nada, o temível esquartejador começa a se esgueirar\npelo chão de madeira, sobe as escadas e foge pelas janelas, correndo pelos telhados noturnos das horas mortas,\no homem contempla a lua e se contenta com sua noite de trabalho.\nPrimeiro final do assassino alcançado (Final:Tirar o fôlego).')
            if (jack_jump_window=='d'):
                print('\tO encapuzado prepara seus punhos e os cerra, ele possui um soco-inglês prateado na mão direita,\no garoto prepara-se para chamar os policiais mas é rapidamente silenciado com uma pancada na bochecha direita,\nele fica atordoado e é tempo o suficiente para o assassino agir, ele acomete outro\ngolpe certeiro contra a face do jovem, ele exagera tanto na força do soco que acaba por\narrancar um dos globos oculares da vítima, que acaba desmaiando devido ao choque, o esquartejador de\nLondres abre a porta do açougue e corre entre a escuridão, assim sumindo e terminando mais uma noite de trabalho.\nSegundo final do assassino alcançado (Final:Imagina se pega nas vistas).')
        if (jack_sub_choices_escape=='l'):
           print('\tO psicopata de White Chapel opta por não adentrar o açougue, ele prepara-se para confrontar os\npoliciais com suas unhas, dentes e armamentos dos mais variados tipos, Jack está com sangue nos olhos.')
           jack_fight_cops=input('\tAtacar os policiais com o punhal desgastado devido ao último ataque(Digite "a")/Atacar os policiais com o soco inglês(Digite "s").')
           if (jack_fight_cops=='s'):
               print('\tO encapuzado cerra os punhos e grita, assim chamando a atenção dos policiais,\neles se aproximam com os cassetetes empunhados e atacam Jack juntos, um dos policiais acerta\na perna direita dele, enquanto o outro limpa o sangue do nariz após receber um golpe certeiro, os\npoliciais atacam juntos novamente, infelizmente, o policial que recebeu o soco ficou atordoado e\nacertou sem querer seu aliado, Jack percebe tal falha e ataca o agressor que estava tonto, o açougueiro de\nWhite Chapel se aproveita da situação e sai correndo do beco, para nunca mais ser visto.\nQuarto final do assassino alcançado (Final:Policiais trapalhões).')
           if (jack_fight_cops=='a'):
               print('\tO encapuzado dá um berro para chamar a atenção dos policiais, os homens se aproximam da figura misteriosa com\nmuita cautela, um dos policiais tenta juntar as mãos de Jack em uma tentativa fútil de o algemar, Jack chuta o\njoelho deste policial e então enfia seu punhal na garganta do mesmo, ele se afoga no próprio sangue,\nentretanto, o punhal fica preso, o outro policial não hesita e puxa um revólver ‘Remington 1888’ de seu coldre,\nacertando assim dois tiros certeiros no peito de Jack e um na cabeça, mas não antes do assassino acertar um tiro no\nbraço dele com a arma roubada do corpo morto.\nTerceiro final do assassino alcançado (Final:Bang Bang Londrino).')
    if (jack_choices1=='p'):
        print('\tO misterioso homem opta por perseguir a testemunha, ela se desespera e começa a correr o mais rápido que pode,\nsua respiração é ofegante, ela claramente está assustada, infelizmente, causar tal sentimento deixa o encapuzado feliz,\nfeliz por saber que mesmo que não consiga finalizar a garota, ele sempre estará nos sonhos, ou melhor, nos pesadelos da mesma.\n\tA jovem começa a arfar, seus passos desaceleram, ela pega uma pequena faca que foi dada pelo seu pai na época\nem que ele atuava ativamente nos Pinkertons, Jack fica cauteloso, ao mesmo tempo em que sorri por baixo da máscara,\nele gosta de vítimas que dão valor a sua vida, ele se prepara e pensa sobre as suas possíveis ações:')
        jack_chasing_options=input('Defender-se dos ataques desferidos pela lâmina.(Digite "d")/Atacar a garota.(Digite "a").')
        if jack_chasing_options=='d':
            jack_defending=input('Ela se joga contra o encapuzado, sua lâmina faz um percurso semelhante à ‘X’,\nJack prepara seus punhos e os coloca em frente ao ataque, as mangas de seu casaco são perfuradas,\ngotas de sangue começam a pingar e sujam suas vestes.\nAgarrar a lâmina da garota e realizar um contra-ataque(Digite "a")/Desviar do golpe(Digite "d").')
            if jack_defending=='a':
                print('\tA menina novamente tenta atacar o assassino, Jack rapidamente segura o braço dela, logo\nlhe dá um soco na barriga, isso faz com que a garota deixe a faca deslizar entre seus dedos,\no assassino pega a faca no ar e rapidamente a golpeia na jugular, os olhos brilhantes da\njovem lentamente se escurecem e Jack termina seu trabalho, um sorriso reluzente é escondido\npela máscara de pano marcada pelo sangue de suas vítimas.\nQuinto final do assassino alcançado (Final: Corte rápido digno de Oscar de edição.)')
            if jack_defending=='d':
                print('\tA garota realiza um ataque semelhante ao último, mas tal ataque com a lâmina é seguido de uma estocada com\no cabo da lâmina, Jack tenta desviar, mas é lento demais, sua cabeça é acertada e isso faz com que\nele fique tonto, a menina novamente ataca Jack, a lâmina acerta em cheio o peito do assassino, a garota aproveita\no momento de fraqueza do encapuzado e corre na direção oposta, o homem se embrulha e agoniza, seus últimos momentos se\nlocalizam em meio ao lixo manchado pelo sangue derramado.\nSexto final do assassino alcançado (Final: Na sarjeta.)')
        if jack_chasing_options=='a':
            jack_attack=input('\tJack abaixa as mangas de seu casaco, revelando assim um soco-inglês dourado, a garota se assusta\nmais ainda e se arrepende por ter puxado a faca, afinal, por mais que ela tivesse ganho aquele pequena faca, a\nmesma nunca foi ensinada a manuseá-la, ela teria que apelar para a única forma de combate que conhecia,\ngolpes desesperados e imprecisos:\nGolpeá-la com o soco inglês.(Digite "g")/Chutar o joelho dela.(Digite "c")/Atirar a faca.(Digite "a").')
            if jack_attack=='g':
                print('\tA garota empunha a faca e suas mãos tremem de maneira violenta, ela tenta acertar o olho de Jack, o\npunho do encapuzado se ergue e é jogado em direção a lâmina, o soco-inglês faz com que a faca fique torta\ne o dedo indicador da menina quebra no processo, o homem golpeia a face da garota repetidas vezes, até se sentir\nsatisfeito com a dose de sofrimento ocasionada pelo mesmo, quando ele termina, seus punhos estão arrebentados,\nmas ele não liga, fez o que almejava para a noite.\nSétimo final do assassino alcançado (Final:Só porrada violenta.)')
            if jack_attack=='c':
                print('\tMesmo com temor, a jovem luta pela sua vida, quando ela tenta acertar o homem, ele se desvia, a lâmina acerta seu\nbraço, Jack chuta o joelho da garota e consequentemente ela cai no chão, Jack pisoteia a cabeça dela até ela se\ntornar algo semelhante a carne moída, as botas de Jack estão encharcadas de sangue, ele resmunga enquanto\nvolta para a sua casa, ele odeia sujar seus sapatos.\nOitavo final do assassino alcançado (Final:Sapatos sujos e problemas com carne.)')
            if jack_attack=='a':
                print('\tA jovem começa a soluçar e chorar, ela sente que seus esforços são em vão, ela ergue a faca e\nrapidamente é interrompida, Jack retirou uma faca por baixo de seu casaco e a atirou com exímia precisão,\na garota se afogou no próprio sangue, Jack começou a andar lentamente para a direção oposta, ele detesta terminar\nseus serviços sem fazer com que a vítima sofra.\nNono final alcançado (Final:Sniper londrino e hipérboles afiadas.)')


